### ISSUE TITLE
hi how do i use this

### ISSUE THREAD

**Issue by ErnerdXD** [Ericspk33/Edpuzzle-Recon#1]
hi how do i use this

**Comment by ericwang0533** [comment]
I updated the README w/ some more detailed steps as well as a demonstration video. If it is still too confusing, feel free to let me know.

**Comment by ErnerdXD** [comment]
can i use it without visual studio code?

**Comment by ericwang0533** [comment]
Yup, as long as you can run the program using Java.

**Comment by Aunnar** [comment]
is this the program that gets you all the answer?

**Comment by ericwang0533** [comment]
No, Edpuzzle fixed that a while ago. This program simply tells you what the questions are, free-response or multiple-choice, at what time, and the answer choices (if it's a multiple-choice question).
