### ISSUE TITLE
Do you have a discord account

### ISSUE THREAD

**Issue by Aunnar** [Ericspk33/Edpuzzle-Recon#2]
Can i have your discord contact and do you know who is tin and midnight

**Comment by Aunnar** [comment]
Also I have a error using it with cmd something like 4 lines

**Comment by Aunnar** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at edpuzzle.main(edpuzzle.java:42)

**Comment by ericwang0533** [comment]
No, I don't know tin and midnight. If you want, you can add `2 patrick klay#6618` 
For the error, can you also send the text that you are copy-pasting into the command line?
